version: '3.8'
services:
  spring-app:
    build: ./backend/
    ports:
      - "8080:8080"
    env_file:
      - ../variaveis-ambientes/remember-quotes/variables.env
    volumes:
      - /var/lib/docker/volumes/remember-quotes/db:/db
  angular-app:
    build: ./frontend/
    ports:
      - "4200:80"